platform:ios, '12.0'
use_frameworks!

target 'FSPopoverView_Example' do
  pod 'FSPopoverView', :path => '../'
end

post_install do |installer|
  installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "Sheng"
  installer.pods_project.targets.each do |target|
    if target.platform_name == :ios then
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
